"""interview session

Revision ID: 4d58e15674a7
Revises: 
Create Date: 2026-06-19 11:02:00.666437
"""
from alembic import op
import sqlalchemy as sa

revision = '4d58e15674a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.String(length=60), nullable=False),
    sa.Column('project_type_id', sa.String(length=80), nullable=True),
    sa.Column('project_name', sa.String(length=200), nullable=True),
    sa.Column('answers_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_session')
    # ### end Alembic commands ###
